#page title
page_title                                : Local Adventure - a game set in Knaresborough, North Yorkshire                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6464050497                                          # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : UK                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/gb/app/local-adventure/id6464050497                                       # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.jmunro89.treasurehuntnative                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app-icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Local Adventure                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A treasure hunt style outdoor adventure game, set in Knaresborough, North Yorkshire. Follow the map and solve puzzles whilst learning about the historic town!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jamie Munro
your_link                                 :
your_city                                 : Knaresborough, North Yorkshire
email_address                             : jmunro89@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : jamiemunro
github_username                           : jmunro89
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Learn local history
    description                           : Learn about the historic town of Knaresborough
    fontawesome_icon_name                 : school
    
  - title                                 : Interactive map
    description                           : Includes a google maps integration to help you find your way
    fontawesome_icon_name                 : map

  - title                                 : Solve puzzles
    description                           : Solve puzzles at each location for a fun challenge
    fontawesome_icon_name                 : puzzle-piece

  - title                                 : Easy and hard questions
    description                           : Change between easy and hard puzzles for all the family to enjoy
    fontawesome_icon_name                 : child

  - title                                 : Play as a group
    description                           : Free to download and play, you can enjoy the adventure together on multiple iOS or Android devices
    fontawesome_icon_name                 : users
  
  - title                                 : Donate to charity
    description                           : Free to play, but please do donate to a local charity using links provided
    fontawesome_icon_name                 : hand-holding-heart

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header-image.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
